# this may be needed to mount 
# https://www.rancher.com/docs/rancher/v1.6/en/cattle/volumes/

services:
  app:
    image: python-pytorch-app-model:latest
    env_file:
      - .env
    container_name: python-pytorch-app-model
    working_dir: /app
    volumes:
      - ./:/app/
    command: ["python", "src/python_docker_uv_app/model.py"]

